### ISSUE TITLE
Victor Emechebe Individual contribution

### ISSUE THREAD

**Issue by Oderindecaleb** [zuri-training/Team-100_AnimaLib#92]

**Comment by Victorasta1** [comment]
# ISSUES WORKED ON AND SOLUTIONS

## Issue Title: Construct the User Flow of The Product

### Issue Link: [#84](https://github.com/zuri-training/Team-100_AnimaLib/issues/84)
### Solution Link: [User Flow](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47582)
I specifically worked on the **Site map**


## Issue Title: Design the page for email verification

### Issue Link: [#75](https://github.com/zuri-training/Team-100_AnimaLib/issues/75)
This Issue came about when we needed to identify if our registered users are who they claim to be. This design would be sent to users (who tried to register) via their email
### Solution Link: [Email verification page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3115%3A18544)


## Issue Title: Design several pages for User Profile in Low Fidelity

### Issue Link: [#39](https://github.com/zuri-training/Team-100_AnimaLib/issues/39)
### Solution Link: [Low fi User Profile](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19428)

## Issue Title: Design several pages for User Profile in High Fidelity

### Issue Link: [#40](https://github.com/zuri-training/Team-100_AnimaLib/issues/40)
### Solution Link: [High fi User Profile](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=3585%3A19426)

## Issue Title: Design Navigation Bar

### Issue Link: [#38](https://github.com/zuri-training/Team-100_AnimaLib/issues/38)
### Solution Link : [Navigation Bar and components](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2831%3A40964)


## Issue Title: Create A style guide consisting of Colour, Typography, Icons, Spacing and Alerts/Notifications

### Issue Link: [#25 ](https://github.com/zuri-training/Team-100_AnimaLib/issues/25)
### Solution Link: [Style Guide page](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=0%3A1)
Below links are the styles i specifically worked on
 [Colour](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=140%3A222)
[Typography](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=146%3A295)


## Issue Title: Brainstorming On Ideas

### Issue Link: [#16 ](https://github.com/zuri-training/Team-100_AnimaLib/issues/16)
### Solution Link:
This issue consists of two solutions. The [Brainstorming ideas](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2880%3A27332) and the [Idea matrix](https://www.figma.com/file/VLaolzmNxT8lx7uBMsYVMz/Team-100_AnimaLib?node-id=2730%3A47674)
